services:
  - type: web
    name: traffic-yolo
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DISABLE_DETECTOR
        value: "1"
